name: Sync Fork

on:
  workflow_dispatch: # check if update works, does it work now

jobs:
  sync:

    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: tgymnich/fork-sync@v1.6.3
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          owner: SuperteamDAO
          base: master
          head: master