name: Sync Fork

on:
  schedule:
    - cron: '*/5 * * * *' # runs every 5 minutes
  workflow_dispatch:

jobs:
  sync:

    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: tgymnich/fork-sync@v1.6.3
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          owner: SuperteamDAO
          base: master
          head: master